export const ROUTES = {
  HOME: '/',
  MAP: '/map',
  POST: '/post',
  ACTIVITY: '/activity',
  ACCOUNT: '/account',
  ACCOUNT_EDIT: '/account/edit',
  LOGIN: '/login',
  REGISTER: '/register',
  MARKETPLACE: '/marketplace',
  TRANSACTIONS: '/transactions',
  PICKUP: '/pickup',
  CHAT: '/chat',
  NOTIFICATIONS: '/notifications',
  REWARDS: '/rewards',
  MISSIONS: '/missions',
  IMPACT: '/impact',
  SUPPORT: '/support',
  SHOP: '/shop',
  RECYCLER: '/recycler',
  ADMIN: '/admin',
} as const
